apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Values.appName }}-external-secret"
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.clusterSecretStore.name }}
    kind: ClusterSecretStore
  target:
    name: "{{ .Values.appName }}-secret"
    creationPolicy: Owner
  data: {{- toYaml .Values.externalSecret.data | nindent 4 }}