replicaCount: 1
appName: calculate-app

image:
  repository: 124355662495.dkr.ecr.eu-north-1.amazonaws.com/calculate-app
  tag: bbcd131d602742ade001f1623fddc74a7d9f9457
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

containerEnv:
  - name: NODE_ENV
    value: development
  - name: DB_HOST
    value: my-postgres-db.ctukiwky8bax.eu-north-1.rds.amazonaws.com
  - name: DB_PORT
    value: "5432"
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: calculate-app-secret
        key: DB_USER
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: calculate-app-secret
        key: DB_PASSWORD
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: calculate-app-secret
        key: DB_NAME
  - name: DB_SSL
    value: "true"

ingress:
  enabled: false
  host: a9cf7db473dc240d291849fdd559ec40-923691792.eu-north-1.elb.amazonaws.com

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

clusterSecretStore:
  name: aws-secrets-manager
  region: eu-north-1

externalSecret:
  data:
    - secretKey: DB_USER # key inside the Kubernetes secret
      remoteRef:
        key: db-secret # aws secrets manager secret name
        property: username # key inside the secret
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db-secret
        property: password
    - secretKey: DB_NAME
      remoteRef:
        key: db-secret
        property: name

serviceAccount:
  create: true
  name: eso-sa    
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::124355662495:role/irsa-secretsmanager-role    
